### ISSUE TITLE
Nested objects?

### ISSUE THREAD

**Issue by kaue** [nickpisacane/CsvBuilder#2]
```
[
    {
        "name": "Kamryn Rempel",
        "age": 48,
        "email": "Fabian.Ernser54@gmail.com",
        "phone":{
              "area": "000",
              "number": "0000000"
         }
    },
    ...
]
```

The header for this object should be `["name", "age", "email", "phone.area", "phone.number"]` ?

**Comment by nickpisacane** [comment]
@kauegimenes sorry for the long wait, and thanks @hstonge for the pull request. In addition to the work by @hstonge, I've added tests for nested properties, and updated the usage docs. Thanks!
