### ISSUE TITLE
Null values

### ISSUE THREAD

**Issue by hounsellal** [nickpisacane/CsvBuilder#5]
I modified line 145 of CsvBuilder.js to accommodate for null values:

col = col.toString() 

I changed to:

col = (col) ? col.toString() : ''

Not sure if there's a better way to deal with this?

**Comment by nickpisacane** [comment]
Nice catch! I wonder though, what would be best case to handle all of the falsy values in JS? `null` and `undefined` seem like they should always be an omitted csv cell. An empty string would be fine on it's own. But, `false` and especially `0` would be cases I would assume might cause unexpected behavior . Maybe, just `null` and `undefined` should return an empty string? Would love a pull request!
